# Generated by Django 5.1.6 on 2025-02-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='analytics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='formlogin_app.productanalytics'),
        ),
        migrations.AlterField(
            model_name='productanalytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='formlogin_app.product'),
        ),
    ]
