# Generated by Django 5.1.4 on 2025-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0002_product_gamer_alter_level_user_alter_points_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investor',
            name='portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='customer',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='sales',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
