# Generated by Django 5.1.6 on 2025-02-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0003_investor_investment_investor_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='formlogin_app.product'),
        ),
    ]
