# Generated by Django 5.1.6 on 2025-02-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0003_product_analytics_alter_productanalytics_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productanalytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_data', to='formlogin_app.product'),
        ),
    ]
