# Generated by Django 5.1.6 on 2025-02-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0004_alter_onlineshop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_shop',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='formlogin_app.onlineshop'),
        ),
    ]
