# Generated by Django 5.1.6 on 2025-02-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0004_alter_productanalytics_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineshop',
            name='customer',
        ),
    ]
