# Generated by Django 5.1.6 on 2025-02-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin_app', '0007_remove_onlineshop_product_alter_product_online_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type': 'seller'}, on_delete=models.deletion.CASCADE,
                                    to='formlogin_app.seller', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='logo',
            field=models.ImageField(default=None, upload_to='logo/'),
        ),
    ]
