# Generated by Django 5.1.6 on 2025-02-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isgamer',
            field=models.BooleanField(default=False),
        ),
    ]
